name: Nightly Upstream Check & Build

on:
  schedule:
    # Run daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no upstream changes'
        required: false
        default: false
        type: boolean

jobs:
  check-and-build:
    runs-on: self-hosted
    timeout-minutes: 720  # 12 hours timeout for the long build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up environment
        run: |
          echo "=== Environment Setup ==="
          echo "Started at: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Force build: ${{ inputs.force_build }}"
          
      - name: Check for upstream changes
        id: upstream_check
        run: |
          echo "=== Checking Upstream ==="
          
          # Make scripts executable if needed
          chmod +x check_upstream.sh smart_update.sh
          
          # Check upstream
          if ./check_upstream.sh; then
            echo "upstream_changed=true" >> $GITHUB_OUTPUT
            echo "✅ Upstream changes detected"
          else
            echo "upstream_changed=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No upstream changes"
          fi
          
      - name: Run smart update (upstream changes detected)
        if: steps.upstream_check.outputs.upstream_changed == 'true'
        run: |
          echo "=== Running Smart Update ==="
          echo "Upstream changes detected, proceeding with build..."
          ./smart_update.sh
          
      - name: Commit PKGBUILD changes (upstream update)
        if: steps.upstream_check.outputs.upstream_changed == 'true'
        run: |
          echo "=== Committing PKGBUILD Changes ==="
          
          # Configure git for the action
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if PKGBUILD was modified
          if git diff --quiet PKGBUILD; then
            echo "No PKGBUILD changes to commit"
          else
            echo "PKGBUILD was modified, committing changes..."
            
            # Get version info for commit message
            PKGVER=$(grep '^pkgver=' PKGBUILD | cut -d'=' -f2)
            PKGREL=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
            
            git add PKGBUILD
            git commit -m "Update to Chromium ${PKGVER}-${PKGREL}

            Automated upstream update from nightly build workflow."
            
            # Push the commit
            git push
            echo "✅ PKGBUILD changes committed and pushed"
          fi
          
      - name: Run forced build (manual trigger)
        if: steps.upstream_check.outputs.upstream_changed == 'false' && inputs.force_build == true
        run: |
          echo "=== Running Forced Build ==="
          echo "No upstream changes but force_build requested..."
          chmod +x do_update.sh
          ./do_update.sh
          
      - name: Commit PKGBUILD changes (forced build)
        if: steps.upstream_check.outputs.upstream_changed == 'false' && inputs.force_build == true
        run: |
          echo "=== Committing PKGBUILD Changes (Forced Build) ==="
          
          # Configure git for the action
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if PKGBUILD was modified
          if git diff --quiet PKGBUILD; then
            echo "No PKGBUILD changes to commit"
          else
            echo "PKGBUILD was modified, committing changes..."
            
            # Get version info for commit message
            PKGVER=$(grep '^pkgver=' PKGBUILD | cut -d'=' -f2)
            PKGREL=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
            
            git add PKGBUILD
            git commit -m "Increment pkgrel to ${PKGVER}-${PKGREL}

            Forced build requested via GitHub Actions workflow."
            
            # Push the commit
            git push
            echo "✅ PKGBUILD changes committed and pushed"
          fi
          
      - name: No action needed
        if: steps.upstream_check.outputs.upstream_changed == 'false' && inputs.force_build != true
        run: |
          echo "=== No Action Needed ==="
          echo "✅ No upstream changes detected and no forced build requested."
          echo "Current state is up-to-date."
          
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.run_id }}
          path: |
            *.log
            nightly_build.log
            cron.log
          retention-days: 7
          
      - name: Summary
        if: always()
        run: |
          echo "=== Build Summary ==="
          echo "Finished at: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Upstream changed: ${{ steps.upstream_check.outputs.upstream_changed }}"
          echo "Force build: ${{ inputs.force_build }}"
          
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Workflow completed successfully"
          else
            echo "❌ Workflow failed - check logs above"
          fi