name: Quick Release (Skip Build)

on:
  push:
    branches:
      - 'release-test/**'
    tags:
      - 'quick-release-*'
  workflow_dispatch:

jobs:
  quick-release:
    runs-on: self-hosted
    timeout-minutes: 30  # Much shorter since we skip the build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure git for SSH
        run: |
          # Configure git to use SSH instead of HTTPS
          git remote set-url origin git@github.com:omacom-io/omarchy-chromium.git
          
          # Configure git user (required for commits)
          git config --local user.email "helmut@januschka.com"
          git config --local user.name "Helmut Januschka"
        
      - name: Set up environment
        run: |
          echo "=== Quick Release Environment ==="
          echo "Started at: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Trigger: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "This workflow uses SKIP_BUILD=1 for testing AUR releases"
          echo "do_update.sh will automatically increment pkgrel"
          
      - name: Check for built Chromium source
        run: |
          echo "=== Checking for Built Chromium Source ==="
          
          CHROMIUM_SRC_DIR="$HOME/omarchy-chromium-src/src"
          
          if [[ ! -d "$CHROMIUM_SRC_DIR" ]]; then
            echo "❌ Chromium source directory not found at $CHROMIUM_SRC_DIR"
            echo "Please run a full build first to create the source checkout"
            exit 1
          fi
          
          # Check if build output exists
          if [[ -f "$CHROMIUM_SRC_DIR/out/Release/chrome" ]]; then
            echo "✅ Found built Chromium at $CHROMIUM_SRC_DIR/out/Release/chrome"
            BUILD_SIZE=$(du -h "$CHROMIUM_SRC_DIR/out/Release/chrome" | cut -f1)
            echo "Chrome binary size: $BUILD_SIZE"
          else
            echo "❌ Built Chrome binary not found at $CHROMIUM_SRC_DIR/out/Release/chrome"
            echo "Please run a full build first"
            exit 1
          fi
          
      - name: Run do_update.sh with SKIP_BUILD=1
        run: |
          echo "=== Running do_update.sh with SKIP_BUILD=1 ==="
          echo "This will increment pkgrel, build from existing binaries, and handle releases"
          
          # Make do_update.sh executable
          chmod +x do_update.sh
          
          # Run do_update.sh with SKIP_BUILD=1
          # This will: increment pkgrel → run SKIP_BUILD=1 makepkg → create GitHub release → update AUR
          SKIP_BUILD=1 ./do_update.sh
          
      - name: Commit PKGBUILD changes (quick release)
        run: |
          echo "=== Committing PKGBUILD Changes (Quick Release) ==="
          
          # Check if PKGBUILD was modified (do_update.sh increments pkgrel)
          if git diff --quiet PKGBUILD; then
            echo "No PKGBUILD changes to commit"
          else
            echo "PKGBUILD was modified, committing changes..."
            
            # Get version info for commit message
            PKGVER=$(grep '^pkgver=' PKGBUILD | cut -d'=' -f2)
            PKGREL=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
            
            git add PKGBUILD
            git commit -m "Quick release ${PKGVER}-${PKGREL}

            Automated quick release via GitHub Actions workflow.
            Built from existing binaries (SKIP_BUILD=1)."
            
            # Push the commit
            git push
            echo "✅ PKGBUILD changes committed and pushed"
          fi
          
      - name: Summary
        if: always()
        run: |
          echo "=== Quick Release Summary ==="
          echo "Finished at: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Purpose: Test AUR release process without rebuilding"
          
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Quick release completed successfully"
            echo "Package has been released to GitHub and AUR updated"
          else
            echo "❌ Quick release failed - check logs above"
          fi