name: Test Self-Hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show system info
        run: |
          echo "=== System Information ==="
          hostname
          whoami
          pwd
          uname -a
          
      - name: Show disk space
        run: |
          echo "=== Disk Space ==="
          df -h
          
      - name: Show available tools
        run: |
          echo "=== Available Tools ==="
          echo "Git version:"
          git --version
          echo "Make version:"
          make --version || echo "make not available"
          echo "GCC version:"
          gcc --version || echo "gcc not available"
          echo "Clang version:"
          clang --version || echo "clang not available"
          echo "Node version:"
          node --version || echo "node not available"
          echo "Python version:"
          python --version || echo "python not available"
          
      - name: Test script permissions
        run: |
          echo "=== Script Permissions ==="
          ls -la *.sh || echo "No .sh files found"
          
      - name: Verify PKGBUILD exists
        run: |
          echo "=== PKGBUILD Check ==="
          if [ -f "PKGBUILD" ]; then
            echo "✅ PKGBUILD found"
            echo "Current version:"
            grep "^pkgver=" PKGBUILD || echo "Could not find pkgver"
          else
            echo "❌ PKGBUILD not found"
          fi
          
      - name: Test upstream check script
        run: |
          echo "=== Testing Upstream Check ==="
          if [ -x "./check_upstream.sh" ]; then
            echo "Running check_upstream.sh..."
            ./check_upstream.sh || echo "Upstream check completed with exit code $?"
          else
            echo "check_upstream.sh not found or not executable"
          fi
          
      - name: Show environment
        run: |
          echo "=== Environment Variables ==="
          echo "HOME: $HOME"
          echo "USER: $USER"
          echo "PATH: $PATH"
          echo "PWD: $PWD"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          
      - name: Test runner success
        run: |
          echo "🎉 Self-hosted runner is working correctly!"
          echo "Runner can execute commands and access the repository."